### ISSUE TITLE
Optimization Loader for GlTF SubAsset

### ISSUE THREAD

**Issue by gz65555** [ant-galaxy/oasis-engine#1071]
**Is your feature request related to a problem? Please describe.**
I have a material only need a texture of glTF asset, but I don't want to parse all the glTF Asset.

**Describe the solution you'd like**
Use `q` as query param. If the param is `textures[0]` which to get `glTFResource.textures[0]`.

```typescript
engine.resourceManager.load('.glTF?q=textures[0]');
engine.resourceManager.load('.glTF?q=materials[0]');
engine.resourceManager.load('.glTF?q=animations[0]');
engine.resourceManager.load('.glTF?q=meshes[0][0]');
engine.resourceManager.load('.glTF?q=defaultSceneRoot');
```

**Additional context**
Support the project of Digital technology. @jeasonstudio

**Comment by GuoLei1990** [comment]
Optimize PR: https://github.com/ant-galaxy/oasis-engine/pull/1299
