### ISSUE TITLE
Animator component should add like goAndStop API

### ISSUE THREAD

**Issue by luzhuang** [ant-galaxy/oasis-engine#1217]
We can use code like this to implement this function but it is not intuitive and inconvenient
![image](https://user-images.githubusercontent.com/10904030/203460419-c9ee1e7f-e3a1-48a0-808f-9553294f7a75.png)

This is a common feature， We should add an API to increase efficiency.

**Comment by GuoLei1990** [comment]
抛开新增API，这个使用方式疑似最奇怪的是 `update(0)`，我现在更关心的 play 切换动画的机制。从用户视角这个功能我完全不会这样，我会倾向更接近你表达想法 `go` and `stop` 的自然 API 对应（2 步）:
1.切换动画： play('agree',0,0.3);
2.暂停动画：`enabled = false;` or `speed=0`

**Comment by luzhuang** [comment]
> 

感觉这样太不直观了

**Comment by luzhuang** [comment]
昨天慎思那提了一个取消叠加的需求（想reset某一层）感觉是不是可以加个pause(name, index, offset) 正好和play对应 offset的含义是停在哪个时间上

**Comment by GuoLei1990** [comment]
> > 
> 
> 感觉这样太不直观了, play里增加update的弊端就是 enable=false的时候 调用play 这个时候模型是会受动画组件影响的，这个感觉不太符合预期

Play 里面特化调用 update 确实不是好的选择，https://github.com/ant-galaxy/oasis-engine/pull/1344 中使用了更自然的方式

**Comment by luzhuang** [comment]
Resolved by https://github.com/ant-galaxy/oasis-engine/pull/1344
