### ISSUE TITLE
`EventDispatcher` dispatch bug when call `off` in  call back.

### ISSUE THREAD

**Issue by GuoLei1990** [ant-galaxy/oasis-engine#1309]
![image](https://user-images.githubusercontent.com/4967545/210322023-8a7109fc-d7b8-4845-8ac5-01f5824aeacc.png)

If developer  write `off` in call back, maybe crash

**Comment by HypnosNova** [comment]
This problem could be solve with an additional map.
My open source EventDispatcher code is here: https://github.com/ValeeraJS/EventFirer/blob/master/src/EventFirer.ts
Code is not good enough but solve this problem. In dispatch method(or fire method in my library), we should check listeners which were already been remove by other listener.
