### ISSUE TITLE
glTF pipleline enhancement

### ISSUE THREAD

**Issue by zhuxudong** [ant-galaxy/oasis-engine#1366]
refs: https://yuque.antfin-inc.com/shensi.zxd/ftoum6/th1n81e0kvlr8yxy

**Comment by meiya163254** [comment]
1. 让引擎外可以访问 gltf parser pipes
![image](https://user-images.githubusercontent.com/73691835/218636617-d21e156c-593a-4def-b954-9fc315529464.png)

2. 可以自由组建 gltf parser pipes, 比如删除一些步骤，增加一些步骤，或者替换一些步骤
