### ISSUE TITLE
支付宝小程序通过 oasis-app.umd.js 文件引入 oasis ，销毁页面后，第二次进入页面白屏问题。

### ISSUE THREAD

**Issue by bxiaotao** [ant-galaxy/oasis-engine#1385]
import {
  start,
  onTouchEnd,
  onTouchStart,
  onTouchCancel,
  onTouchMove,
} from "./oasis-app/oasis-app.umd";

const useExpARLoader = my.getSystemInfoSync().platform == "Android";;
Page({
  onLoad(){

  },
  onShow(){
  },
  onCanvasReady() {
    var startFunc = function (value) {
      my._createCanvas({
        id: "canvas",
        success: (canvas) => {
          console.log("创建canvas成功",canvas)
          if (canvas) {
            const info = my.getSystemInfoSync(); // 屏幕常亮
            const { windowWidth, windowHeight, pixelRatio, titleBarHeight } =
              info;
            // @ts-ignore
            my.setKeepScreenOn({
              keepScreenOn: true,
            });
            canvas.width = windowWidth * pixelRatio;
            canvas.height = (windowHeight - titleBarHeight) * pixelRatio;
            console.log("输出canvas", canvas, "value", value)
            start(canvas, value);
            
          } else {
            throw "success but no canvas";
          }
        },
      })
    };
    if (useExpARLoader) {
      if (!ExpARLoader) {
        console.info("[MY] onReady: expARLoader not defined");
      } else {
        ExpARLoader.load({
          success: function () {
            console.log("ExpARLoader load Success");
            startFunc('')
          },
          fail: function (obj) {
            console.log("ExpARLoader load fail:", obj);
          }
        })
      }
    } else {
      startFunc('')
    }
  },
  onTouchStart(e) {
    onTouchStart(e);
  },
  onTouchMove(e) {
    onTouchMove(e);
  },
  onTouchEnd(e) {
    onTouchEnd(e);
  },
  onTouchCancel(e) {
    onTouchCancel(e);
  },
  
})

**Comment by cptbtptpbcptdtptp** [comment]
看起来你手上的模版很旧，可以找给你模版的人更新一下。
