### ISSUE TITLE
小块兽从 0.9.0 beta66 升级 beta67 后出现错误的剔除

### ISSUE THREAD

**Issue by yuufen** [ant-galaxy/oasis-engine#1398]

**Comment by yuufen** [comment]
更正：beta65 升级 beta66

**Comment by zhuxudong** [comment]
引擎在 [包围盒](https://github.com/ant-galaxy/oasis-engine/commit/60a0f70c039d08cc8f8999755585f995bcfa9af7#diff-53d45dff3b3dde43761c134944f01708bc98d5b9949b05fa85d101c1047f967dR292-R294) 优化中，针对没有根骨骼（skeleton） 的情况做了兜底处理，即 localBounds = mesh.bounds,因此当美术资产导出没有根骨骼的情况时，无法保证一定是正确的包围盒。

这种情况 @GuoLei1990 看看怎么处理比较合适
![Uploading image.png…]()
