### ISSUE TITLE
gltf model rendering error

### ISSUE THREAD

**Issue by cptbtptpbcptdtptp** [ant-galaxy/oasis-engine#342]
**Describe the bug**
When rendering the gltf model, there is a rectangular area that is not rendered.

**To Reproduce**
Can be reproduced here：https://oasisengine.cn/0.4/docs/material-cn#unlitmaterial

**Screenshots**
![image](https://user-images.githubusercontent.com/7768919/122372128-01aa1d00-cf93-11eb-8cc1-c9f6baebd5e2.png)

**Desktop (please complete the following information):**
 - OS: [MacBook Pro (16-inch, 2019)]
 - Browser [版本 81.0.4044.138（正式版本） （64 位）]
 - Version [0.4.0 alpha.2]

**Comment by GuoLei1990** [comment]
The problem has disappeared
