### ISSUE TITLE
Uncaught TypeError: Cannot read property 'cloneTo' of undefined

### ISSUE THREAD

**Issue by shuai-fan** [ant-galaxy/oasis-engine#811]
使用gltf-pipeline把glb转换成gltf之后，模型在gltf-viewer查看正常显示， 拆分材质时候无法加载模型 
日志提示extensionsRequired: KHR_materials_pbrSpecularGlossiness
报错 Uncaught TypeError: Cannot read property 'cloneTo' of undefined
请问是需要添加什么插件支持吗

**Comment by cptbtptpbcptdtptp** [comment]
https://oasisengine.cn/gltf-viewer 这里可以显示吗？
方便发一下模型吗？

**Comment by GuoLei1990** [comment]
需要提供素材进一步确认问题，由于缺少复现路径，暂时关闭！
